### PR TITLE
modbus: probe checks for known function

### PR DESCRIPTION
**Pull request by catenacyber**
cc @cccs-sadugas 
Does this make sense ?

### CODE REVIEW

**Comment by catenacyber** [comment]
Friendly ping @cccs-sadugas or @cccs-rtmorti ?

**Review by cccs-sadugas — COMMENTED** [review]
Is this from an issue you are seeing with Suricata? The spec allows for function codes outside of the public assigned ranges (page 10 of [Modbus Application Protocol V1b](https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf)).

We could make this feature optional by adding a configuration option to the `Modbus` parser struct.

**Comment by catenacyber** [comment]
> Is this from an issue you are seeing with Suricata?

Yes

> We could make this feature optional by adding a configuration option to the Modbus parser struct.

I am okay with this solution, who should implement it ?

**Comment by cccs-sadugas** [comment]
> > Is this from an issue you are seeing with Suricata?
> 
> Yes

Can you describe the issue that prompted this PR in more detail?

> 
> > We could make this feature optional by adding a configuration option to the Modbus parser struct.
> 
> I am okay with this solution, who should implement it?

We can have a look at it and release with the next version of SAWP.

**Comment by catenacyber** [comment]
> Can you describe the issue that prompted this PR in more detail?

The payload 
`04000000 00132020 00000000 20202020 20202020 20202020 20` gets recognized as Modbus by the probing parser.

Do you see a better fix ?

**Comment by cccs-sadugas** [comment]
> Do you see a better fix ?

I think what we discussed is a great start. We could also add a configuration option for additional function codes a user wants to probe. Does Suricata's probing only look at the first packet in a session and then decide whether to keep or drop the parser for that session?

Looking at the documentation [here](https://suricata.readthedocs.io/en/suricata-6.0.5/rules/modbus-keyword.html?highlight=modbus) it seems we want to keep support for rules like `modbus: function user`.

The fix is ready and will be released shortly.

**Comment by catenacyber** [comment]
>  Does Suricata's probing only look at the first packet in a session and then decide whether to keep or drop the parser for that session?

Basically yes.
I can give you a more detailed version of the truth if you wish...

**Comment by cccs-sadugas** [comment]
> Basically yes. I can give you a more detailed version of the truth if you wish...

Sure, I'm always interested in learning more about the inner workings of Suricata :)

Here is the feature in version 0.10.0 which is now released: https://github.com/CybercentreCanada/sawp/commit/62fa1c56cd3fa815bf59c338ae74369a756e26f5

Thanks for your contribution!

**Pull request closed without merging**
